export const INTEGRATIONS = [
  {
    key:         'ghl_agent',
    label:       'GHL Agent Studio',
    icon:        '🤖',
    color:       'rgba(34,197,94,0.12)',
    description: 'Trigger a GHL Agent Studio agent to build native funnels, websites and automations inside GHL.',
    docsUrl:     'https://help.gohighlevel.com/support/solutions/articles/155000003649',
    fields: [
      { key: 'webhookUrl', label: 'Agent Trigger Webhook URL', type: 'password', placeholder: 'https://services.leadconnectorhq.com/hooks/...' },
    ],
  },
  {
    key:         'perplexity',
    label:       'Perplexity AI',
    icon:        '🔍',
    color:       'rgba(99,102,241,0.12)',
    description: 'AI-powered web research and real-time information retrieval.',
    docsUrl:     'https://docs.perplexity.ai',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'pplx-...' },
    ],
  },
  {
    key:         'openai',
    label:       'OpenAI',
    icon:        '✨',
    color:       'rgba(16,185,129,0.1)',
    description: 'GPT-4o content generation and DALL-E 3 image creation.',
    docsUrl:     'https://platform.openai.com/api-keys',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'sk-...' },
    ],
  },
  {
    key:         'facebook_ads',
    label:       'Facebook Ads',
    icon:        '📘',
    color:       'rgba(24,119,242,0.1)',
    description: 'Manage campaigns, ad sets, creatives and read Ads Library.',
    docsUrl:     'https://developers.facebook.com/docs/marketing-api',
    fields: [
      { key: 'accessToken', label: 'User Access Token (optional)', type: 'password', placeholder: 'EAABs... (leave blank if connected via OAuth)' },
      { key: 'adAccountId', label: 'Ad Account ID',     type: 'text',     placeholder: 'XXXXXXXXXX (numbers only, without act_ prefix)' },
    ],
  },
  {
    key:         'sendgrid',
    label:       'SendGrid',
    icon:        '📧',
    color:       'rgba(0,168,168,0.1)',
    description: 'Transactional and marketing email delivery at scale.',
    docsUrl:     'https://app.sendgrid.com/settings/api_keys',
    fields: [
      { key: 'apiKey',    label: 'API Key',   type: 'password', placeholder: 'SG...' },
      { key: 'fromEmail', label: 'From Email', type: 'email',    placeholder: 'hello@yourdomain.com' },
      { key: 'fromName',  label: 'From Name',  type: 'text',     placeholder: 'Your Brand' },
    ],
  },
  {
    key:         'slack',
    label:       'Slack',
    icon:        '💬',
    color:       'rgba(74,21,75,0.15)',
    description: 'Send messages and notifications to Slack channels.',
    docsUrl:     'https://api.slack.com/apps',
    fields: [
      { key: 'webhookUrl',     label: 'Incoming Webhook URL', type: 'password', placeholder: 'https://hooks.slack.com/services/...' },
      { key: 'defaultChannel', label: 'Default Channel',      type: 'text',     placeholder: '#general' },
    ],
  },
  {
    key:         'apollo',
    label:       'Apollo.io',
    icon:        '🚀',
    color:       'rgba(249,115,22,0.1)',
    description: 'B2B contact enrichment, lead search and prospecting.',
    docsUrl:     'https://developer.apollo.io',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Your Apollo API key' },
    ],
  },
  {
    key:         'heygen',
    label:       'HeyGen',
    icon:        '🎬',
    color:       'rgba(168,85,247,0.1)',
    description: 'AI avatar video generation for personalised outreach.',
    docsUrl:     'https://app.heygen.com/settings?nav=API',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Your HeyGen API key' },
    ],
  },
  {
    key:         'hubspot',
    label:       'HubSpot',
    icon:        '🟠',
    color:       'rgba(255,122,0,0.1)',
    description: 'CRM contacts, deals and pipeline management via HubSpot.',
    docsUrl:     'https://app.hubspot.com/private-apps',
    fields: [
      { key: 'accessToken', label: 'Private App Token', type: 'password', placeholder: 'pat-na1-...' },
    ],
  },
  {
    key:         'keap',
    label:       'Keap (Infusionsoft)',
    icon:        '🌀',
    color:       'rgba(0,163,224,0.1)',
    description: 'CRM contacts, tags and automations via Keap.',
    docsUrl:     'https://keys.developer.keap.com/accounts',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Your Keap service account key' },
    ],
  },
  {
    key:         'manychat',
    label:       'ManyChat',
    icon:        '💙',
    color:       'rgba(0,132,255,0.1)',
    description: 'Automate Facebook Messenger, Instagram and SMS conversations.',
    docsUrl:     'https://api.manychat.com',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Your ManyChat API key' },
    ],
  },
  {
    key:         'google_my_business',
    label:       'Google Business Profile',
    icon:        '📍',
    color:       'rgba(66,133,244,0.1)',
    description: 'Manage Google Business Profile listings, reviews and replies.',
    docsUrl:     'https://developers.google.com/my-business',
    fields: [
      { key: 'accessToken', label: 'OAuth Access Token', type: 'password', placeholder: 'ya29...' },
    ],
  },
  {
    key:         'shopify',
    label:       'Shopify',
    icon:        '🛍️',
    color:       'rgba(149,191,71,0.1)',
    description: 'Read orders, products and customers; create discount codes.',
    docsUrl:     'https://shopify.dev/docs/api/admin-rest',
    fields: [
      { key: 'shopDomain',  label: 'Shop Domain',        type: 'text',     placeholder: 'mystore.myshopify.com' },
      { key: 'accessToken', label: 'Admin Access Token', type: 'password', placeholder: 'shpat_...' },
    ],
  },
  {
    key:         'woocommerce',
    label:       'WooCommerce',
    icon:        '🛒',
    color:       'rgba(150,88,138,0.1)',
    description: 'Manage WooCommerce orders, products, customers and coupons.',
    docsUrl:     'https://woocommerce.github.io/woocommerce-rest-api-docs/',
    fields: [
      { key: 'siteUrl',        label: 'Site URL',        type: 'text',     placeholder: 'https://mysite.com' },
      { key: 'consumerKey',    label: 'Consumer Key',    type: 'text',     placeholder: 'ck_...' },
      { key: 'consumerSecret', label: 'Consumer Secret', type: 'password', placeholder: 'cs_...' },
    ],
  },
  {
    key:         'google_calendar',
    label:       'Google Calendar',
    icon:        '📅',
    color:       'rgba(26,115,232,0.1)',
    description: 'List, create and delete Google Calendar events.',
    docsUrl:     'https://developers.google.com/calendar/api',
    fields: [
      { key: 'accessToken', label: 'OAuth Access Token', type: 'password', placeholder: 'ya29...' },
      { key: 'calendarId',  label: 'Calendar ID',        type: 'text',     placeholder: 'primary or calendar@group.calendar.google.com' },
    ],
  },
  {
    key:         'linkedin',
    label:       'LinkedIn',
    icon:        '💼',
    color:       'rgba(0,119,181,0.1)',
    description: 'LinkedIn Ads analytics and organic post publishing.',
    docsUrl:     'https://developer.linkedin.com',
    fields: [
      { key: 'accessToken', label: 'OAuth Access Token', type: 'password', placeholder: 'AQV...' },
      { key: 'adAccountId', label: 'Ad Account ID',      type: 'text',     placeholder: '123456789 (numbers only)' },
    ],
  },
  {
    key:         'google_contacts',
    label:       'Google Contacts',
    icon:        '👥',
    color:       'rgba(52,168,83,0.1)',
    description: 'List, search and create Google Contacts via People API.',
    docsUrl:     'https://developers.google.com/people',
    fields: [
      { key: 'accessToken', label: 'OAuth Access Token', type: 'password', placeholder: 'ya29...' },
    ],
  },
  {
    key:         'google_forms',
    label:       'Google Forms',
    icon:        '📋',
    color:       'rgba(123,31,162,0.1)',
    description: 'Retrieve Google Forms structure and collect responses.',
    docsUrl:     'https://developers.google.com/forms/api',
    fields: [
      { key: 'accessToken', label: 'OAuth Access Token', type: 'password', placeholder: 'ya29...' },
    ],
  },
  {
    key:         'airtable',
    label:       'Airtable',
    icon:        '🗂️',
    color:       'rgba(252,182,65,0.1)',
    description: 'Read, create and update Airtable records across any base.',
    docsUrl:     'https://airtable.com/developers/web/api/introduction',
    fields: [
      { key: 'apiKey', label: 'Personal Access Token', type: 'password', placeholder: 'patXXXX...' },
      { key: 'baseId', label: 'Base ID',               type: 'text',     placeholder: 'appXXXXXXXXXXXXXX' },
    ],
  },
  {
    key:         'monday',
    label:       'Monday.com',
    icon:        '📌',
    color:       'rgba(255,80,0,0.1)',
    description: 'Manage Monday.com boards, items and status updates.',
    docsUrl:     'https://developer.monday.com/api-reference',
    fields: [
      { key: 'apiToken', label: 'API Token', type: 'password', placeholder: 'eyJhbGci...' },
    ],
  },
  {
    key:         'typeform',
    label:       'Typeform',
    icon:        '📝',
    color:       'rgba(36,36,36,0.08)',
    description: 'Fetch Typeform forms and collect survey responses.',
    docsUrl:     'https://developer.typeform.com',
    fields: [
      { key: 'accessToken', label: 'Personal Access Token', type: 'password', placeholder: 'tfp_...' },
    ],
  },
  {
    key:         'asana',
    label:       'Asana',
    icon:        '✅',
    color:       'rgba(252,99,107,0.1)',
    description: 'List, create and complete Asana tasks and projects.',
    docsUrl:     'https://developers.asana.com/docs',
    fields: [
      { key: 'accessToken', label: 'Personal Access Token', type: 'password', placeholder: '1/1234...' },
    ],
  },
  {
    key:         'canva',
    label:       'Canva',
    icon:        '🎨',
    color:       'rgba(0,199,183,0.1)',
    description: 'Browse and export Canva designs via Connect API.',
    docsUrl:     'https://www.canva.com/developers',
    fields: [
      { key: 'accessToken', label: 'OAuth Access Token', type: 'password', placeholder: 'Your Canva access token' },
    ],
  },
  {
    key:         'tiktok_ads',
    label:       'TikTok Ads',
    icon:        '🎵',
    color:       'rgba(0,0,0,0.06)',
    description: 'Manage TikTok ad campaigns and pull performance analytics.',
    docsUrl:     'https://business-api.tiktok.com/portal/docs',
    fields: [
      { key: 'accessToken',  label: 'Access Token',   type: 'password', placeholder: 'Your TikTok Marketing API token' },
      { key: 'advertiserId', label: 'Advertiser ID',  type: 'text',     placeholder: '7123456789012345678' },
    ],
  },
  {
    key:         'google_ads',
    label:       'Google Ads',
    icon:        '📢',
    color:       'rgba(251,188,5,0.12)',
    description: 'Google Ads campaigns and lead form submission data.',
    docsUrl:     'https://developers.google.com/google-ads/api/docs/start',
    fields: [
      { key: 'accessToken',    label: 'OAuth Access Token', type: 'password', placeholder: 'ya29...' },
      { key: 'customerId',     label: 'Customer ID',        type: 'text',     placeholder: '1234567890 (no dashes)' },
      { key: 'developerToken', label: 'Developer Token',    type: 'password', placeholder: 'Your Google Ads developer token' },
    ],
  },
  {
    key:         'openrouter',
    label:       'OpenRouter',
    icon:        '🔀',
    color:       'rgba(99,102,241,0.1)',
    description: 'Access 100+ AI models (GPT-4, Claude, Gemini, Llama) via one API.',
    docsUrl:     'https://openrouter.ai/docs',
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'sk-or-v1-...' },
    ],
  },
  {
    key:         'gravity_forms',
    label:       'Gravity Forms',
    icon:        '⚡',
    color:       'rgba(255,153,0,0.1)',
    description: 'Pull Gravity Forms entries from WordPress sites.',
    docsUrl:     'https://docs.gravityforms.com/rest-api-v2/',
    fields: [
      { key: 'siteUrl',        label: 'WordPress Site URL', type: 'text',     placeholder: 'https://mysite.com' },
      { key: 'consumerKey',    label: 'Consumer Key',       type: 'text',     placeholder: 'ck_...' },
      { key: 'consumerSecret', label: 'Consumer Secret',    type: 'password', placeholder: 'cs_...' },
    ],
  },
  {
    key:         'http_client',
    label:       'HTTP Client / Webhook Tester',
    icon:        '🌐',
    color:       'rgba(107,114,128,0.1)',
    description: 'Send HTTP requests to any URL — great for webhook testing and custom APIs.',
    docsUrl:     'https://developer.mozilla.org/en-US/docs/Web/HTTP',
    fields: [
      { key: 'baseUrl',        label: 'Base URL',          type: 'text',     placeholder: 'https://api.example.com' },
      { key: 'defaultHeaders', label: 'Default Headers',   type: 'text',     placeholder: '{"Authorization":"Bearer token"}' },
    ],
  },
];

export const INTEGRATION_MAP = Object.fromEntries(INTEGRATIONS.map(i => [i.key, i]));
